# Generated by Django 5.0 on 2023-12-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='addresss',
            new_name='address',
        ),
    ]
